# config.py — Central configuration

TICKERS = ["RELIANCE.NS", "TCS.NS", "^NSEI"]

INITIAL_WALLET        = 100_000.0
TRADE_ALLOCATION      = 0.10
MAX_CONCURRENT_TRADES = 3

SLIPPAGE_PCT          = 0.0005
BROKERAGE_PCT         = 0.0003

OPTION_PREMIUM_PCT    = 0.015
RISK_FREE_RATE        = 0.065
DAYS_TO_EXPIRY        = 7
IMPLIED_VOLATILITY    = 0.20

TRAILING_STOP_PCT     = 0.012

MACD_FAST     = 12
MACD_SLOW     = 26
MACD_SIGNAL   = 9
SUPERTREND_PERIOD = 10
SUPERTREND_MULT   = 3.0
SMA_PERIOD    = 200
EMA_FAST      = 20
EMA_SLOW      = 50

DATA_INTERVAL = "1m"
DATA_PERIOD   = "5d"
DATA_DIR      = "data"
STALE_HOURS   = 6

TICKS_PER_CANDLE  = 60
GBM_SIGMA_SCALE   = 0.3
